import { NextRequest, NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { getCurrentUser } from "@/lib/auth"

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await getCurrentUser(request)
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  const { id } = await params
  const document = await prisma.document.findFirst({
    where: { id, userId: user.id },
    include: { analysis: true },
  })

  if (!document) {
    return NextResponse.json({ error: "Document not found" }, { status: 404 })
  }

  const analysis = document.analysis

  const markdown = generateMarkdown(document, analysis)

  return new NextResponse(markdown, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="${document.originalName.replace(/\.[^/.]+$/, "")}-analysis.md"`,
    },
  })
}

function generateMarkdown(document: any, analysis: any): string {
  const lines: string[] = []

  lines.push(`# Document Analysis: ${document.originalName}`)
  lines.push("")
  lines.push(`**Date:** ${new Date(document.createdAt).toLocaleDateString()}`)
  lines.push(`**File Type:** ${document.fileType}`)
  lines.push(`**File Size:** ${(document.fileSize / 1024).toFixed(1)} KB`)
  lines.push(`**Status:** ${document.status}`)
  lines.push("")

  if (analysis) {
    if (analysis.documentType) {
      lines.push(`**Document Type:** ${analysis.documentType}`)
    }
    if (analysis.confidenceScore) {
      lines.push(`**AI Confidence:** ${(analysis.confidenceScore * 100).toFixed(0)}%`)
    }
    if (analysis.tone) {
      lines.push(`**Tone:** ${analysis.tone}`)
    }
    lines.push("")
    lines.push("---")
    lines.push("")

    if (analysis.shortSummary) {
      lines.push("## Short Summary")
      lines.push("")
      lines.push(analysis.shortSummary)
      lines.push("")
    }

    if (analysis.detailedSummary) {
      lines.push("## Detailed Summary")
      lines.push("")
      lines.push(analysis.detailedSummary)
      lines.push("")
    }

    if (analysis.keyPoints && Array.isArray(analysis.keyPoints) && analysis.keyPoints.length > 0) {
      lines.push("## Key Points")
      lines.push("")
      for (const point of analysis.keyPoints) {
        lines.push(`- ${point}`)
      }
      lines.push("")
    }

    if (analysis.risks && Array.isArray(analysis.risks) && analysis.risks.length > 0) {
      lines.push("## Risks & Alerts")
      lines.push("")
      for (const risk of analysis.risks) {
        lines.push(`- ⚠️ ${risk}`)
      }
      lines.push("")
    }

    if (analysis.suggestedActions && Array.isArray(analysis.suggestedActions) && analysis.suggestedActions.length > 0) {
      lines.push("## Suggested Actions")
      lines.push("")
      for (const action of analysis.suggestedActions) {
        lines.push(`- ${action}`)
      }
      lines.push("")
    }

    if (analysis.keywords && Array.isArray(analysis.keywords) && analysis.keywords.length > 0) {
      lines.push("## Keywords")
      lines.push("")
      lines.push(analysis.keywords.map((k: string) => `\`${k}\``).join(", "))
      lines.push("")
    }

    if (analysis.suggestedQuestions && Array.isArray(analysis.suggestedQuestions) && analysis.suggestedQuestions.length > 0) {
      lines.push("## Suggested Questions")
      lines.push("")
      for (const q of analysis.suggestedQuestions) {
        lines.push(`- ${q}`)
      }
      lines.push("")
    }
  }

  if (document.extractedText) {
    lines.push("---")
    lines.push("")
    lines.push("## Extracted Text Preview")
    lines.push("")
    lines.push("```")
    lines.push(document.extractedText.slice(0, 2000))
    if (document.extractedText.length > 2000) {
      lines.push("")
      lines.push("... (truncated)")
    }
    lines.push("```")
    lines.push("")
  }

  lines.push("---")
  lines.push(`*Generated by ClarioDocs on ${new Date().toLocaleString()}*`)
  lines.push("")

  return lines.join("\n")
}
